package com.example.catapult.breeds.repository

import com.example.catapult.data.ui.BreedUiModel

val SampleData = listOf (
    BreedUiModel (
        id = "abys",
        name = "Abyssinian",
        altNames = listOf(),
        description = "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
        temperament = listOf("Active", "Energetic", "Independent", "Intelligent", "Gentle"),
        origins = listOf("Egypt"),
        lifeSpan = "14 - 15",
        weight = listOf("7 - 10", "3 - 5"),
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 3,
        intelligence = 5,
        sheddingLevel = 2,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
        imageUrl = "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    ),
    BreedUiModel (
        id = "aege",
        name = "Aegean",
        altNames = listOf(),
        description = "Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.",
        temperament = listOf("Affectionate", "Social", "Intelligent", "Playful", "Active"),
        origins = listOf("Greece"),
        lifeSpan = "9 - 12",
        weight = listOf("7 - 10", "3 - 5"),
        adaptability = 5,
        affectionLevel = 4,
        childFriendly = 4,
        intelligence = 3,
        sheddingLevel = 3,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/Aegean_cat",
        imageUrl = "https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg",
    ),
    BreedUiModel(
        id = "abob",
        name = "American Bobtail",
        altNames = listOf(),
        description = "American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.",
        temperament = listOf("Intelligent", "Interactive", "Lively", "Playful", "Sensitive"),
        origins = listOf("United States"),
        lifeSpan = "11 - 15",
        weight = listOf("7 - 16", "3 - 7"),
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        intelligence = 5,
        sheddingLevel = 3,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/American_Bobtail",
        imageUrl = "https://cdn2.thecatapi.com/images/hBXicehMA.jpg",
    ),
    BreedUiModel(
        id = "acur",
        name = "American Curl",
        altNames = listOf(),
        description = "Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.",
        temperament = listOf("Affectionate", "Curious", "Intelligent", "Interactive", "Lively", "Playful", "Social"),
        origins = listOf("United States"),
        lifeSpan = "12 - 16",
        weight = listOf("5 - 10", "2 - 5"),
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        intelligence = 3,
        sheddingLevel = 3,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/American_Curl",
        imageUrl = "https://cdn2.thecatapi.com/images/xnsqonbjW.jpg",
    ),
    BreedUiModel(
        id = "asho",
        name = "American Shorthair",
        altNames = listOf("Domestic Shorthair"),
        description = "The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.",
        temperament = listOf("Active", "Curious", "Easy Going", "Playful", "Calm"),
        origins = listOf("United States"),
        lifeSpan = "15 - 17",
        weight = listOf("8 - 15", "4 - 7"),
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        intelligence = 3,
        sheddingLevel = 3,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/American_Shorthair",
        imageUrl = "https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg",
    ),
    BreedUiModel(
        id = "awir",
        name = "American Wirehair",
        altNames = listOf(),
        description = "The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.",
        temperament = listOf("Affectionate", "Curious", "Gentle", "Intelligent", "Interactive", "Lively", "Loyal", "Playful", "Sensible", "Social"),
        origins = listOf("United States"),
        lifeSpan = "14 - 18",
        weight = listOf("8 - 15", "4 - 7"),
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        intelligence = 3,
        sheddingLevel = 1,
        rare = 0,
        wikipediaUrl = "https://en.wikipedia.org/wiki/American_Wirehair",
        imageUrl ="https://cdn2.thecatapi.com/images/8D--jCd21.jpg",
    )
)